### ISSUE TITLE
[Unhandled Command]

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGatev2#35]
Zigate V2 firmware 321

```
2022-03-30 17:54:49,725 INFO    : [   ZiGateWriter_2] _sendData to ZiGate NOW  - [54] 0042 5d00
2022-03-30 17:54:49,734 INFO    : [ZiGateForwarder_2] Decod8000 Received         [  ] PacketType:  5d00 TypeSqn: 00 sqn_app: 00/0 sqn_aps: 75/117 Status: [02] npdu: 00 apdu: 03
2022-03-30 17:54:49,736 ERROR   : [ZiGateForwarder_2] Decode8000 - PacketType: 5d00 TypeSqn: 00 sqn_app: 00 sqn_aps: 75 Status: [Unhandled Command]

```

```
2022-03-30 18:04:07,443 INFO    : [   ZiGateWriter_2] _sendData to ZiGate NOW  - [193] 0100 02e5f001230000000000000200040005
2022-03-30 18:04:07,448 INFO    : [ZiGateForwarder_2] Decod8000 Received         [  ] PacketType:  e5f0 TypeSqn: 00 sqn_app: 00/0 sqn_aps: c4/196 Status: [02] npdu: 00 apdu: 03
2022-03-30 18:04:07,449 ERROR   : [ZiGateForwarder_2] Decode8000 - PacketType: e5f0 TypeSqn: 00 sqn_app: 00 sqn_aps: c4 Status: [Unhandled Command]
```

Arrived also on a Zigate user : https://easydomoticz.com/forum/viewtopic.php?p=103961#p103961
Never see this on Zigate V1

**Comment by fairecasoimeme** [comment]
Hi, could you give the value of [unhandled command] . What is the hexadecimal value of status ?

**Comment by pipiche38** [comment]
Status: [02]  => 0x02

**Comment by fairecasoimeme** [comment]
OK,
From my understanding, the status mean that the command sent is not correct. The packet type correspond to nothing known.
indeed command 0x5d00 or 0xe5f0 are unknown.

if you see for example [193] 0100 02e5f001230000000000000200040005
0xe5f0 correspond to the target short addr. it seems that's the request is truncated (it miss the destination endpoint too)

from [54] 0042 5d00, 0x5d00 is the short address not the packet type. It's look like that it miss some datas

**Comment by pipiche38** [comment]
0x0042 is a node descriptor request. As far as I know the Zigate is expecting the Short ID which is given . I do not see any missing datas. 

As the Read Attribute Request, I also do not see any missing datas
Source Ep: 0x01
Dst Epo: 0x23
Cluster 0x0000
Direction: 0x00
Manuf flag: 0x00
Manuf Code: 0x0000
Nb Attribut: 0x02
List of Attribute 0x0004 , 0x0005

0100 02 e5f0 01 23 0000 00 00 0000 02 0004 0005

**Comment by fairecasoimeme** [comment]
Sorry, I got screwed by the 0x23 dest ep that is not common.
There is also checksum and size of the packet that we don't see in your logs.
(for example a real raw data for a node request packet is : 0x0042 0x0002 0xB9 0xD62F )

That I don't undestand is why the 0x8000 decoded use the short address instead of the command. For me there are shifts or loss data. If this issue appear all of the time, this mean that there are a translation issue but in this case, the only explanation is a loss datas

There is no other issue in the log before of after ?

**Comment by pipiche38** [comment]
Ep 0x23 is an Ep found on Friend devices like the motion sensors.
And even if we look to the 0x0042 there is only one parameter expected which is the short id, I don't see much room for lost of data here, as Decode8000 is bringing them back in a total wrong namer.

This happening only on ZiGateV2 and not they is no error before or after. it just happening time to time.

**Comment by fairecasoimeme** [comment]
The fact that the 0x8000 decoder take the short address instead of the real packet type show (in my opinion) that there is a lost or shift datas

Even if the plugins sent the right packet, perhaps the ZiGate received a part of it. 

To understand the phenomenom, we need complete RAW datas (with checksum) or sniff trace.

Which ZiGatev2 was used (PiZiGate+ or USB versions) ?

**Comment by fairecasoimeme** [comment]
If i see the las post from the user : He has a PiZiGate V1 with a 3.1e version updated now to a 3.21(OPDM)
