### ISSUE TITLE
How to Send Large Unicast messages Where Data length exceeds 100 bytes

### ISSUE THREAD

**Issue by dmsherazi** [fairecasoimeme/ZiGatev2#55]
I have to implement a custom command for zigate to send some data to another device. The data will be longer than the APDU is steup (100). I see that I have two options

1) Add another APDU type that can support upto 1024 bytes
2) Set Maximum Number of Simultaneous Data Requests to arround 10 and send with `ZPS_eAplAfUnicastAckDataReq()`

Which one would be best approach?

I didn't yet tried the  first one, but in the second case I am facing an issue. I can send the packet but when I capture the DATA_INDICATION_EVENT at the recieving node which is a zigate V2 - set as a router device with the zigate v2 firmware. I see the payload size is 100 only. I couldnt find how can I get the data back defragmented ?

**Comment by dmsherazi** [comment]
!

**Comment by fairecasoimeme** [comment]
Hi,
you cannot increase the APDU up to 1024 bytes because protocol limits.
Set Maximum Number of Simultaneous Data Requests to arround 10 does not solve your problem.
The best practice is to develop your own protocol on zigbee 3.0 with for example a new sequence number and fragment your data with 100 byte packets.

Zigbee3.0 is not a good protocol for this use case. It is not developed to handle large unicast messages.
